dist: xenial
language: python
cache: pip
python:
- 3.5
- 3.6
- 3.7
- 3.8
install:
- make install
scripts: echo foo
deploy:
  provider: pypi
  user: __token__
  password:
    secure: E8j8UiINgNg+5KuvNVgexlffTEAUwc7SXAM9NKfB244L7bZTTTh9CNOe8cUEi/VXnAPgoFROs3E5uTmuycS+oHrtrYYAArqcTSzvH1sw34LqrUIDx+veSggjcP/p3nBQVgYYQAlzzylad9XodTIXeeeI+p+GRoGLWKJ23kzeVsZMTtZcv/cd94DzF8C1A7sX+XsBBXMFLuIu5z/rx6sr1MRoQf0xvByem2E4p8XO5GykSTUwqaVwXhHrhj+2aONgntY3Kfwfvo3+gZYM14pose2XMLhrdDrnCkBzyH9fq9hnu1ocvh8/ddb1CWq74ZSHg9VG1TzD5ZwsHhbBJqbCM8flkdH1xeGDcvffoNxVVNQKRmpLrJ28gv8swF9YMnLBPmOI6s9IjEc9BJ3XLT5GImKS2J46k3YcUseQsDs1XOqJ+eBYpPRq2sEO2scwrJIlflVHs6xkyrKinwrQXMC8E7FES0uRzwUN/NIZLfY9qPOFDOxlpIvy4ZardZS8fIkExWrbMPnXQhG/fBeMkEyZQnkkUkk6OavU8YUslom1dZFDJONd0aMrbdDOUWfKhH3864wkTFAbm5hMeJUhus3hQr7ozUnDOnv+duAGALWx49cbcMO/3e19vCSlpo1BrpFeV6s29hOQbqucVkczX/t7BaUm3EN1aR6o2qAgXFaPMcc=
  on:
    branch: master
